# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160624084513 on 2016-07-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('price_per_night', models.IntegerField(default=0)),
            ],
        ),
    ]
