# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160624084513 on 2016-07-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='destination',
            field=models.CharField(default='', max_length=100),
        ),
    ]
